# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from invoicepdfs.models.batch_item_input import BatchItemInput
from invoicepdfs.models.batch_output_options import BatchOutputOptions
from typing import Optional, Set
from typing_extensions import Self

class BatchCreateRequest(BaseModel):
    """
    BatchCreateRequest
    """ # noqa: E501
    operation: Optional[StrictStr] = 'render'
    items: Annotated[List[BatchItemInput], Field(min_length=1)]
    template_id: Optional[StrictStr] = 'tpl_modern'
    output: Optional[BatchOutputOptions] = None
    __properties: ClassVar[List[str]] = ["operation", "items", "template_id", "output"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['render']):
            raise ValueError("must be one of enum values ('render')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation") if obj.get("operation") is not None else 'render',
            "items": [BatchItemInput.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "template_id": obj.get("template_id") if obj.get("template_id") is not None else 'tpl_modern',
            "output": BatchOutputOptions.from_dict(obj["output"]) if obj.get("output") is not None else None
        })
        return _obj


