# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BrandingProfileOut(BaseModel):
    """
    BrandingProfileOut
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    is_default: StrictBool
    logo_file_id: Optional[StrictStr] = None
    primary_color: StrictStr
    accent_color: StrictStr
    font_family: Optional[StrictStr] = None
    header_text: Optional[StrictStr] = None
    footer_text: StrictStr
    hide_invoicepdfs_branding: StrictBool
    created_at: StrictStr
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["id", "name", "is_default", "logo_file_id", "primary_color", "accent_color", "font_family", "header_text", "footer_text", "hide_invoicepdfs_branding", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandingProfileOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if logo_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.logo_file_id is None and "logo_file_id" in self.model_fields_set:
            _dict['logo_file_id'] = None

        # set to None if font_family (nullable) is None
        # and model_fields_set contains the field
        if self.font_family is None and "font_family" in self.model_fields_set:
            _dict['font_family'] = None

        # set to None if header_text (nullable) is None
        # and model_fields_set contains the field
        if self.header_text is None and "header_text" in self.model_fields_set:
            _dict['header_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandingProfileOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "is_default": obj.get("is_default"),
            "logo_file_id": obj.get("logo_file_id"),
            "primary_color": obj.get("primary_color"),
            "accent_color": obj.get("accent_color"),
            "font_family": obj.get("font_family"),
            "header_text": obj.get("header_text"),
            "footer_text": obj.get("footer_text"),
            "hide_invoicepdfs_branding": obj.get("hide_invoicepdfs_branding"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


