# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DocumentStatus(str, Enum):
    """
    The document lifecycle. The transitions between these live in app/documents/base.py, which is the only thing that moves a document.
    """

    """
    allowed enum values
    """
    DRAFT = 'draft'
    FINALIZED = 'finalized'
    SENT = 'sent'
    PAID = 'paid'
    VOID = 'void'
    ARCHIVED = 'archived'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DocumentStatus from a JSON string"""
        return cls(json.loads(json_str))


