# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class DocumentTypeOut(BaseModel):
    """
    DocumentTypeOut
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    number_prefix: StrictStr
    payable: StrictBool
    requires_source_document: StrictBool
    supports_reason: StrictBool
    line_item_type: StrictStr
    actions: List[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "name", "number_prefix", "payable", "requires_source_document", "supports_reason", "line_item_type", "actions"]

    @field_validator('line_item_type')
    def line_item_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['standard', 'shipped']):
            raise ValueError("must be one of enum values ('standard', 'shipped')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentTypeOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentTypeOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "number_prefix": obj.get("number_prefix"),
            "payable": obj.get("payable"),
            "requires_source_document": obj.get("requires_source_document"),
            "supports_reason": obj.get("supports_reason"),
            "line_item_type": obj.get("line_item_type"),
            "actions": obj.get("actions")
        })
        return _obj


