# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DocumentBrandingInput(BaseModel):
    """
    DocumentBrandingInput
    """ # noqa: E501
    logo_file_id: Optional[StrictStr] = None
    primary_color: Optional[StrictStr] = '#111827'
    accent_color: Optional[StrictStr] = '#111827'
    font_family: Optional[StrictStr] = None
    footer_text: Optional[StrictStr] = 'Generated by InvoicePDFs'
    __properties: ClassVar[List[str]] = ["logo_file_id", "primary_color", "accent_color", "font_family", "footer_text"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentBrandingInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if logo_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.logo_file_id is None and "logo_file_id" in self.model_fields_set:
            _dict['logo_file_id'] = None

        # set to None if font_family (nullable) is None
        # and model_fields_set contains the field
        if self.font_family is None and "font_family" in self.model_fields_set:
            _dict['font_family'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentBrandingInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "logo_file_id": obj.get("logo_file_id"),
            "primary_color": obj.get("primary_color") if obj.get("primary_color") is not None else '#111827',
            "accent_color": obj.get("accent_color") if obj.get("accent_color") is not None else '#111827',
            "font_family": obj.get("font_family"),
            "footer_text": obj.get("footer_text") if obj.get("footer_text") is not None else 'Generated by InvoicePDFs'
        })
        return _obj


