# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from invoicepdfs.models.document_invoice_data_input import DocumentInvoiceDataInput
from invoicepdfs.models.document_output_options import DocumentOutputOptions
from invoicepdfs.models.document_template_ref import DocumentTemplateRef
from typing import Optional, Set
from typing_extensions import Self

class DocumentRenderRequest(BaseModel):
    """
    DocumentRenderRequest
    """ # noqa: E501
    document_type: Optional[StrictStr] = 'invoice'
    data: DocumentInvoiceDataInput
    template: DocumentTemplateRef
    output: Optional[DocumentOutputOptions] = None
    __properties: ClassVar[List[str]] = ["document_type", "data", "template", "output"]

    @field_validator('document_type')
    def document_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note']):
            raise ValueError("must be one of enum values ('invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentRenderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentRenderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "document_type": obj.get("document_type") if obj.get("document_type") is not None else 'invoice',
            "data": DocumentInvoiceDataInput.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "template": DocumentTemplateRef.from_dict(obj["template"]) if obj.get("template") is not None else None,
            "output": DocumentOutputOptions.from_dict(obj["output"]) if obj.get("output") is not None else None
        })
        return _obj


