# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from invoicepdfs.models.invoice_totals_out import InvoiceTotalsOut
from typing import Optional, Set
from typing_extensions import Self

class InvoiceOut(BaseModel):
    """
    InvoiceOut
    """ # noqa: E501
    id: StrictStr
    status: StrictStr
    invoice_number: StrictStr
    document_type: StrictStr
    issue_date: date
    due_date: Optional[date] = None
    currency: StrictStr
    locale: Optional[StrictStr] = None
    business_profile_id: StrictStr
    customer_id: StrictStr
    invoice: Dict[str, Any]
    totals: InvoiceTotalsOut
    created_at: StrictStr
    updated_at: StrictStr
    finalized_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "status", "invoice_number", "document_type", "issue_date", "due_date", "currency", "locale", "business_profile_id", "customer_id", "invoice", "totals", "created_at", "updated_at", "finalized_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['draft', 'finalized', 'sent', 'paid', 'void', 'archived']):
            raise ValueError("must be one of enum values ('draft', 'finalized', 'sent', 'paid', 'void', 'archived')")
        return value

    @field_validator('document_type')
    def document_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note']):
            raise ValueError("must be one of enum values ('invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['due_date'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if finalized_at (nullable) is None
        # and model_fields_set contains the field
        if self.finalized_at is None and "finalized_at" in self.model_fields_set:
            _dict['finalized_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "invoice_number": obj.get("invoice_number"),
            "document_type": obj.get("document_type"),
            "issue_date": obj.get("issue_date"),
            "due_date": obj.get("due_date"),
            "currency": obj.get("currency"),
            "locale": obj.get("locale"),
            "business_profile_id": obj.get("business_profile_id"),
            "customer_id": obj.get("customer_id"),
            "invoice": obj.get("invoice"),
            "totals": InvoiceTotalsOut.from_dict(obj["totals"]) if obj.get("totals") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "finalized_at": obj.get("finalized_at")
        })
        return _obj


