# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from invoicepdfs.models.invoice_branding_input import InvoiceBrandingInput
from invoicepdfs.models.invoice_custom_field_input import InvoiceCustomFieldInput
from invoicepdfs.models.invoice_discount_input import InvoiceDiscountInput
from invoicepdfs.models.invoice_line_item_input import InvoiceLineItemInput
from invoicepdfs.models.invoice_note_input import InvoiceNoteInput
from invoicepdfs.models.invoice_payment_input import InvoicePaymentInput
from invoicepdfs.models.invoice_shipping_input import InvoiceShippingInput
from invoicepdfs.models.invoice_term_input import InvoiceTermInput
from invoicepdfs.models.postal_address import PostalAddress
from typing import Optional, Set
from typing_extensions import Self

class InvoiceDraftRequest(BaseModel):
    """
    InvoiceDraftRequest
    """ # noqa: E501
    invoice_number: StrictStr
    document_type: Optional[StrictStr] = 'invoice'
    issue_date: date
    due_date: Optional[date] = None
    currency: StrictStr
    locale: Optional[StrictStr] = None
    business_profile_id: StrictStr
    customer_id: StrictStr
    ship_to: Optional[PostalAddress] = None
    line_items: List[InvoiceLineItemInput]
    discounts: Optional[List[InvoiceDiscountInput]] = None
    shipping: Optional[InvoiceShippingInput] = None
    notes: Optional[List[InvoiceNoteInput]] = None
    terms: Optional[List[InvoiceTermInput]] = None
    custom_fields: Optional[List[InvoiceCustomFieldInput]] = None
    payment: Optional[InvoicePaymentInput] = None
    branding: Optional[InvoiceBrandingInput] = None
    __properties: ClassVar[List[str]] = ["invoice_number", "document_type", "issue_date", "due_date", "currency", "locale", "business_profile_id", "customer_id", "ship_to", "line_items", "discounts", "shipping", "notes", "terms", "custom_fields", "payment", "branding"]

    @field_validator('document_type')
    def document_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note']):
            raise ValueError("must be one of enum values ('invoice', 'credit_note', 'quote', 'receipt', 'proforma', 'purchase_order', 'delivery_note')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceDraftRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ship_to
        if self.ship_to:
            _dict['ship_to'] = self.ship_to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item in self.line_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['line_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in discounts (list)
        _items = []
        if self.discounts:
            for _item in self.discounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['discounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of shipping
        if self.shipping:
            _dict['shipping'] = self.shipping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item in self.notes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['notes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in terms (list)
        _items = []
        if self.terms:
            for _item in self.terms:
                if _item:
                    _items.append(_item.to_dict())
            _dict['terms'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item in self.custom_fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['payment'] = self.payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of branding
        if self.branding:
            _dict['branding'] = self.branding.to_dict()
        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['due_date'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if ship_to (nullable) is None
        # and model_fields_set contains the field
        if self.ship_to is None and "ship_to" in self.model_fields_set:
            _dict['ship_to'] = None

        # set to None if shipping (nullable) is None
        # and model_fields_set contains the field
        if self.shipping is None and "shipping" in self.model_fields_set:
            _dict['shipping'] = None

        # set to None if payment (nullable) is None
        # and model_fields_set contains the field
        if self.payment is None and "payment" in self.model_fields_set:
            _dict['payment'] = None

        # set to None if branding (nullable) is None
        # and model_fields_set contains the field
        if self.branding is None and "branding" in self.model_fields_set:
            _dict['branding'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceDraftRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invoice_number": obj.get("invoice_number"),
            "document_type": obj.get("document_type") if obj.get("document_type") is not None else 'invoice',
            "issue_date": obj.get("issue_date"),
            "due_date": obj.get("due_date"),
            "currency": obj.get("currency"),
            "locale": obj.get("locale"),
            "business_profile_id": obj.get("business_profile_id"),
            "customer_id": obj.get("customer_id"),
            "ship_to": PostalAddress.from_dict(obj["ship_to"]) if obj.get("ship_to") is not None else None,
            "line_items": [InvoiceLineItemInput.from_dict(_item) for _item in obj["line_items"]] if obj.get("line_items") is not None else None,
            "discounts": [InvoiceDiscountInput.from_dict(_item) for _item in obj["discounts"]] if obj.get("discounts") is not None else None,
            "shipping": InvoiceShippingInput.from_dict(obj["shipping"]) if obj.get("shipping") is not None else None,
            "notes": [InvoiceNoteInput.from_dict(_item) for _item in obj["notes"]] if obj.get("notes") is not None else None,
            "terms": [InvoiceTermInput.from_dict(_item) for _item in obj["terms"]] if obj.get("terms") is not None else None,
            "custom_fields": [InvoiceCustomFieldInput.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "payment": InvoicePaymentInput.from_dict(obj["payment"]) if obj.get("payment") is not None else None,
            "branding": InvoiceBrandingInput.from_dict(obj["branding"]) if obj.get("branding") is not None else None
        })
        return _obj


