# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from invoicepdfs.models.invoice_draft_request import InvoiceDraftRequest
from typing import Optional, Set
from typing_extensions import Self

class RecurringInvoicePatchRequest(BaseModel):
    """
    RecurringInvoicePatchRequest
    """ # noqa: E501
    frequency: Optional[StrictStr] = None
    interval: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    end_date: Optional[date] = None
    max_occurrences: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    numbering_sequence_id: Optional[StrictStr] = None
    auto_finalize: Optional[StrictBool] = None
    invoice_template: Optional[InvoiceDraftRequest] = None
    __properties: ClassVar[List[str]] = ["frequency", "interval", "end_date", "max_occurrences", "numbering_sequence_id", "auto_finalize", "invoice_template"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecurringInvoicePatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of invoice_template
        if self.invoice_template:
            _dict['invoice_template'] = self.invoice_template.to_dict()
        # set to None if frequency (nullable) is None
        # and model_fields_set contains the field
        if self.frequency is None and "frequency" in self.model_fields_set:
            _dict['frequency'] = None

        # set to None if interval (nullable) is None
        # and model_fields_set contains the field
        if self.interval is None and "interval" in self.model_fields_set:
            _dict['interval'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if max_occurrences (nullable) is None
        # and model_fields_set contains the field
        if self.max_occurrences is None and "max_occurrences" in self.model_fields_set:
            _dict['max_occurrences'] = None

        # set to None if numbering_sequence_id (nullable) is None
        # and model_fields_set contains the field
        if self.numbering_sequence_id is None and "numbering_sequence_id" in self.model_fields_set:
            _dict['numbering_sequence_id'] = None

        # set to None if auto_finalize (nullable) is None
        # and model_fields_set contains the field
        if self.auto_finalize is None and "auto_finalize" in self.model_fields_set:
            _dict['auto_finalize'] = None

        # set to None if invoice_template (nullable) is None
        # and model_fields_set contains the field
        if self.invoice_template is None and "invoice_template" in self.model_fields_set:
            _dict['invoice_template'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecurringInvoicePatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "frequency": obj.get("frequency"),
            "interval": obj.get("interval"),
            "end_date": obj.get("end_date"),
            "max_occurrences": obj.get("max_occurrences"),
            "numbering_sequence_id": obj.get("numbering_sequence_id"),
            "auto_finalize": obj.get("auto_finalize"),
            "invoice_template": InvoiceDraftRequest.from_dict(obj["invoice_template"]) if obj.get("invoice_template") is not None else None
        })
        return _obj


