# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TemplateConfig(BaseModel):
    """
    What a custom template is: a built-in design plus the brand to render it in.  A custom template is not a design of its own — it names one of the built-ins in ``base_template_id`` and carries the values below, which are the same ones ``data.branding`` carries. They are applied *underneath* a request's own branding, so a document that states a colour still wins and one template can serve several brands.  Typed rather than the free-form object it used to be: nothing read that object, so every key in it was equally correct and a caller could keep sending ``primary_colour`` forever without a word back. Unset here means \"the template has no opinion\" — unlike ``Branding``, whose every field has a non-empty default and so cannot say that.
    """ # noqa: E501
    primary_color: Optional[Annotated[str, Field(strict=True)]] = None
    accent_color: Optional[Annotated[str, Field(strict=True)]] = None
    font_family: Optional[StrictStr] = None
    header_text: Optional[StrictStr] = None
    footer_text: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["primary_color", "accent_color", "font_family", "header_text", "footer_text"]

    @field_validator('primary_color')
    def primary_color_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$", value):
            raise ValueError(r"must validate the regular expression /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/")
        return value

    @field_validator('accent_color')
    def accent_color_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$", value):
            raise ValueError(r"must validate the regular expression /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if primary_color (nullable) is None
        # and model_fields_set contains the field
        if self.primary_color is None and "primary_color" in self.model_fields_set:
            _dict['primary_color'] = None

        # set to None if accent_color (nullable) is None
        # and model_fields_set contains the field
        if self.accent_color is None and "accent_color" in self.model_fields_set:
            _dict['accent_color'] = None

        # set to None if font_family (nullable) is None
        # and model_fields_set contains the field
        if self.font_family is None and "font_family" in self.model_fields_set:
            _dict['font_family'] = None

        # set to None if header_text (nullable) is None
        # and model_fields_set contains the field
        if self.header_text is None and "header_text" in self.model_fields_set:
            _dict['header_text'] = None

        # set to None if footer_text (nullable) is None
        # and model_fields_set contains the field
        if self.footer_text is None and "footer_text" in self.model_fields_set:
            _dict['footer_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primary_color": obj.get("primary_color"),
            "accent_color": obj.get("accent_color"),
            "font_family": obj.get("font_family"),
            "header_text": obj.get("header_text"),
            "footer_text": obj.get("footer_text")
        })
        return _obj


