# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.webhook_endpoint_response import WebhookEndpointResponse

class TestWebhookEndpointResponse(unittest.TestCase):
    """WebhookEndpointResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEndpointResponse:
        """Test WebhookEndpointResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEndpointResponse`
        """
        model = WebhookEndpointResponse()
        if include_optional:
            return WebhookEndpointResponse(
                data = invoicepdfs.models.webhook_endpoint_out.WebhookEndpointOut(
                    id = '', 
                    url = '', 
                    description = '', 
                    events = [
                        ''
                        ], 
                    is_active = True, 
                    created_at = '', 
                    updated_at = '', )
            )
        else:
            return WebhookEndpointResponse(
                data = invoicepdfs.models.webhook_endpoint_out.WebhookEndpointOut(
                    id = '', 
                    url = '', 
                    description = '', 
                    events = [
                        ''
                        ], 
                    is_active = True, 
                    created_at = '', 
                    updated_at = '', ),
        )
        """

    def testWebhookEndpointResponse(self):
        """Test WebhookEndpointResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
