# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.batch_items_list_response import BatchItemsListResponse

class TestBatchItemsListResponse(unittest.TestCase):
    """BatchItemsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchItemsListResponse:
        """Test BatchItemsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchItemsListResponse`
        """
        model = BatchItemsListResponse()
        if include_optional:
            return BatchItemsListResponse(
                data = [
                    invoicepdfs.models.batch_item_out.BatchItemOut(
                        id = '', 
                        external_id = '', 
                        document_type = '', 
                        status = 'pending', 
                        render_id = '', 
                        error_message = '', 
                        created_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return BatchItemsListResponse(
                data = [
                    invoicepdfs.models.batch_item_out.BatchItemOut(
                        id = '', 
                        external_id = '', 
                        document_type = '', 
                        status = 'pending', 
                        render_id = '', 
                        error_message = '', 
                        created_at = '', )
                    ],
        )
        """

    def testBatchItemsListResponse(self):
        """Test BatchItemsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
