# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health
        """
        pass

    def test_ready_ready_get(self) -> None:
        """Test case for ready_ready_get

        Ready
        """
        pass

    def test_version_version_get(self) -> None:
        """Test case for version_version_get

        Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
