# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.stats_overview import StatsOverview

class TestStatsOverview(unittest.TestCase):
    """StatsOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsOverview:
        """Test StatsOverview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsOverview`
        """
        model = StatsOverview()
        if include_optional:
            return StatsOverview(
                counts = invoicepdfs.models.stats_counts.StatsCounts(
                    invoices = 56, 
                    customers = 56, 
                    business_profiles = 56, ),
                invoice_status_counts = {
                    'key' : 56
                    },
                recent_invoices = [
                    invoicepdfs.models.stats_recent_invoice.StatsRecentInvoice(
                        id = '', 
                        invoice_number = '', 
                        document_type = '', 
                        status = '', 
                        currency = '', 
                        total_amount = '', 
                        issue_date = '', )
                    ]
            )
        else:
            return StatsOverview(
                counts = invoicepdfs.models.stats_counts.StatsCounts(
                    invoices = 56, 
                    customers = 56, 
                    business_profiles = 56, ),
                invoice_status_counts = {
                    'key' : 56
                    },
                recent_invoices = [
                    invoicepdfs.models.stats_recent_invoice.StatsRecentInvoice(
                        id = '', 
                        invoice_number = '', 
                        document_type = '', 
                        status = '', 
                        currency = '', 
                        total_amount = '', 
                        issue_date = '', )
                    ],
        )
        """

    def testStatsOverview(self):
        """Test StatsOverview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
