# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.invoices_api import InvoicesApi


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_archive_invoice_api_v1_invoices_invoice_id_archive_post(self) -> None:
        """Test case for archive_invoice_api_v1_invoices_invoice_id_archive_post

        Archive Invoice
        """
        pass

    def test_calculate_invoice_api_v1_invoices_calculate_post(self) -> None:
        """Test case for calculate_invoice_api_v1_invoices_calculate_post

        Calculate Invoice
        """
        pass

    def test_create_invoice_api_v1_invoices_post(self) -> None:
        """Test case for create_invoice_api_v1_invoices_post

        Create Invoice
        """
        pass

    def test_delete_invoice_api_v1_invoices_invoice_id_delete(self) -> None:
        """Test case for delete_invoice_api_v1_invoices_invoice_id_delete

        Delete Invoice
        """
        pass

    def test_duplicate_invoice_api_v1_invoices_invoice_id_duplicate_post(self) -> None:
        """Test case for duplicate_invoice_api_v1_invoices_invoice_id_duplicate_post

        Duplicate Invoice
        """
        pass

    def test_finalize_invoice_api_v1_invoices_invoice_id_finalize_post(self) -> None:
        """Test case for finalize_invoice_api_v1_invoices_invoice_id_finalize_post

        Finalize Invoice
        """
        pass

    def test_get_invoice_api_v1_invoices_invoice_id_get(self) -> None:
        """Test case for get_invoice_api_v1_invoices_invoice_id_get

        Get Invoice
        """
        pass

    def test_list_invoice_deliveries_api_v1_invoices_invoice_id_deliveries_get(self) -> None:
        """Test case for list_invoice_deliveries_api_v1_invoices_invoice_id_deliveries_get

        List Invoice Deliveries
        """
        pass

    def test_list_invoices_api_v1_invoices_get(self) -> None:
        """Test case for list_invoices_api_v1_invoices_get

        List Invoices
        """
        pass

    def test_mark_paid_api_v1_invoices_invoice_id_mark_paid_post(self) -> None:
        """Test case for mark_paid_api_v1_invoices_invoice_id_mark_paid_post

        Mark Paid
        """
        pass

    def test_mark_sent_api_v1_invoices_invoice_id_mark_sent_post(self) -> None:
        """Test case for mark_sent_api_v1_invoices_invoice_id_mark_sent_post

        Mark Sent
        """
        pass

    def test_mark_unpaid_api_v1_invoices_invoice_id_mark_unpaid_post(self) -> None:
        """Test case for mark_unpaid_api_v1_invoices_invoice_id_mark_unpaid_post

        Mark Unpaid
        """
        pass

    def test_patch_invoice_api_v1_invoices_invoice_id_patch(self) -> None:
        """Test case for patch_invoice_api_v1_invoices_invoice_id_patch

        Patch Invoice
        """
        pass

    def test_preview_invoice_api_v1_invoices_preview_post(self) -> None:
        """Test case for preview_invoice_api_v1_invoices_preview_post

        Preview Invoice
        """
        pass

    def test_render_invoice_api_v1_invoices_invoice_id_renders_post(self) -> None:
        """Test case for render_invoice_api_v1_invoices_invoice_id_renders_post

        Render Invoice
        """
        pass

    def test_replace_invoice_api_v1_invoices_invoice_id_put(self) -> None:
        """Test case for replace_invoice_api_v1_invoices_invoice_id_put

        Replace Invoice
        """
        pass

    def test_restore_invoice_api_v1_invoices_invoice_id_restore_post(self) -> None:
        """Test case for restore_invoice_api_v1_invoices_invoice_id_restore_post

        Restore Invoice
        """
        pass

    def test_send_invoice_api_v1_invoices_invoice_id_send_post(self) -> None:
        """Test case for send_invoice_api_v1_invoices_invoice_id_send_post

        Send Invoice
        """
        pass

    def test_validate_invoice_api_v1_invoices_validate_post(self) -> None:
        """Test case for validate_invoice_api_v1_invoices_validate_post

        Validate Invoice
        """
        pass

    def test_void_invoice_api_v1_invoices_invoice_id_void_post(self) -> None:
        """Test case for void_invoice_api_v1_invoices_invoice_id_void_post

        Void Invoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
