# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.invoice_term_input import InvoiceTermInput

class TestInvoiceTermInput(unittest.TestCase):
    """InvoiceTermInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceTermInput:
        """Test InvoiceTermInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceTermInput`
        """
        model = InvoiceTermInput()
        if include_optional:
            return InvoiceTermInput(
                type = 'term',
                content = 'Net 30 — payment due within 30 days of invoice date.'
            )
        else:
            return InvoiceTermInput(
                type = 'term',
                content = 'Net 30 — payment due within 30 days of invoice date.',
        )
        """

    def testInvoiceTermInput(self):
        """Test InvoiceTermInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
