# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.line_item_discount_input import LineItemDiscountInput

class TestLineItemDiscountInput(unittest.TestCase):
    """LineItemDiscountInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LineItemDiscountInput:
        """Test LineItemDiscountInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LineItemDiscountInput`
        """
        model = LineItemDiscountInput()
        if include_optional:
            return LineItemDiscountInput(
                type = 'percentage',
                value = '10',
                reason = ''
            )
        else:
            return LineItemDiscountInput(
                value = '10',
        )
        """

    def testLineItemDiscountInput(self):
        """Test LineItemDiscountInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
