# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.tax_rates_list_response import TaxRatesListResponse

class TestTaxRatesListResponse(unittest.TestCase):
    """TaxRatesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxRatesListResponse:
        """Test TaxRatesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxRatesListResponse`
        """
        model = TaxRatesListResponse()
        if include_optional:
            return TaxRatesListResponse(
                data = [
                    invoicepdfs.models.tax_rate_out.TaxRateOut(
                        id = '', 
                        name = '', 
                        rate = '', 
                        inclusive = True, 
                        jurisdiction = '', 
                        is_active = True, 
                        created_at = '', 
                        updated_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return TaxRatesListResponse(
                data = [
                    invoicepdfs.models.tax_rate_out.TaxRateOut(
                        id = '', 
                        name = '', 
                        rate = '', 
                        inclusive = True, 
                        jurisdiction = '', 
                        is_active = True, 
                        created_at = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testTaxRatesListResponse(self):
        """Test TaxRatesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
