# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_forgot_password_api_v1_auth_forgot_password_post(self) -> None:
        """Test case for forgot_password_api_v1_auth_forgot_password_post

        Forgot Password
        """
        pass

    def test_logout_api_v1_auth_logout_post(self) -> None:
        """Test case for logout_api_v1_auth_logout_post

        Logout
        """
        pass

    def test_me_api_v1_auth_me_get(self) -> None:
        """Test case for me_api_v1_auth_me_get

        Me
        """
        pass

    def test_patch_me_api_v1_auth_me_patch(self) -> None:
        """Test case for patch_me_api_v1_auth_me_patch

        Patch Me
        """
        pass

    def test_refresh_api_v1_auth_refresh_post(self) -> None:
        """Test case for refresh_api_v1_auth_refresh_post

        Refresh
        """
        pass

    def test_register_api_v1_auth_register_post(self) -> None:
        """Test case for register_api_v1_auth_register_post

        Register
        """
        pass

    def test_reset_password_api_v1_auth_reset_password_post(self) -> None:
        """Test case for reset_password_api_v1_auth_reset_password_post

        Reset Password
        """
        pass

    def test_token_exchange_api_v1_auth_token_post(self) -> None:
        """Test case for token_exchange_api_v1_auth_token_post

        Token Exchange
        """
        pass


if __name__ == '__main__':
    unittest.main()
