# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.template_versions_api import TemplateVersionsApi


class TestTemplateVersionsApi(unittest.TestCase):
    """TemplateVersionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplateVersionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_template_version_api_v1_templates_template_id_versions_post(self) -> None:
        """Test case for create_template_version_api_v1_templates_template_id_versions_post

        Create Template Version
        """
        pass

    def test_get_template_version_api_v1_templates_template_id_versions_version_get(self) -> None:
        """Test case for get_template_version_api_v1_templates_template_id_versions_version_get

        Get Template Version
        """
        pass

    def test_list_template_versions_api_v1_templates_template_id_versions_get(self) -> None:
        """Test case for list_template_versions_api_v1_templates_template_id_versions_get

        List Template Versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
