# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.import_out import ImportOut

class TestImportOut(unittest.TestCase):
    """ImportOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportOut:
        """Test ImportOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportOut`
        """
        model = ImportOut()
        if include_optional:
            return ImportOut(
                id = '',
                source_format = '',
                status = 'pending',
                total_rows = 56,
                imported_rows = 56,
                failed_rows = 56,
                errors = [
                    { }
                    ],
                created_at = '',
                updated_at = '',
                completed_at = ''
            )
        else:
            return ImportOut(
                id = '',
                source_format = '',
                status = 'pending',
                total_rows = 56,
                imported_rows = 56,
                failed_rows = 56,
                created_at = '',
                updated_at = '',
        )
        """

    def testImportOut(self):
        """Test ImportOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
