# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.document_render_options import DocumentRenderOptions

class TestDocumentRenderOptions(unittest.TestCase):
    """DocumentRenderOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentRenderOptions:
        """Test DocumentRenderOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentRenderOptions`
        """
        model = DocumentRenderOptions()
        if include_optional:
            return DocumentRenderOptions(
                template_id = 'tpl_modern',
                page_size = 'LETTER',
                expires_in = 56
            )
        else:
            return DocumentRenderOptions(
        )
        """

    def testDocumentRenderOptions(self):
        """Test DocumentRenderOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
