# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.recurring_invoices_api import RecurringInvoicesApi


class TestRecurringInvoicesApi(unittest.TestCase):
    """RecurringInvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecurringInvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recurring_invoice(self) -> None:
        """Test case for cancel_recurring_invoice

        Cancel Recurring Invoice
        """
        pass

    def test_create_recurring_invoice(self) -> None:
        """Test case for create_recurring_invoice

        Create Recurring Invoice
        """
        pass

    def test_get_recurring_invoice(self) -> None:
        """Test case for get_recurring_invoice

        Get Recurring Invoice
        """
        pass

    def test_list_generated_invoices(self) -> None:
        """Test case for list_generated_invoices

        List Generated Invoices
        """
        pass

    def test_list_recurring_invoices(self) -> None:
        """Test case for list_recurring_invoices

        List Recurring Invoices
        """
        pass

    def test_pause_recurring_invoice(self) -> None:
        """Test case for pause_recurring_invoice

        Pause Recurring Invoice
        """
        pass

    def test_resume_recurring_invoice(self) -> None:
        """Test case for resume_recurring_invoice

        Resume Recurring Invoice
        """
        pass

    def test_update_recurring_invoice(self) -> None:
        """Test case for update_recurring_invoice

        Update Recurring Invoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
