# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.document_types_list_response import DocumentTypesListResponse

class TestDocumentTypesListResponse(unittest.TestCase):
    """DocumentTypesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentTypesListResponse:
        """Test DocumentTypesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentTypesListResponse`
        """
        model = DocumentTypesListResponse()
        if include_optional:
            return DocumentTypesListResponse(
                data = [
                    invoicepdfs.models.document_type_out.DocumentTypeOut(
                        id = '', 
                        name = '', 
                        number_prefix = '', 
                        payable = True, 
                        requires_source_document = True, 
                        supports_reason = True, 
                        line_item_type = 'standard', 
                        actions = [
                            ''
                            ], )
                    ]
            )
        else:
            return DocumentTypesListResponse(
                data = [
                    invoicepdfs.models.document_type_out.DocumentTypeOut(
                        id = '', 
                        name = '', 
                        number_prefix = '', 
                        payable = True, 
                        requires_source_document = True, 
                        supports_reason = True, 
                        line_item_type = 'standard', 
                        actions = [
                            ''
                            ], )
                    ],
        )
        """

    def testDocumentTypesListResponse(self):
        """Test DocumentTypesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
