# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.api_request_logs_list_response import ApiRequestLogsListResponse

class TestApiRequestLogsListResponse(unittest.TestCase):
    """ApiRequestLogsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiRequestLogsListResponse:
        """Test ApiRequestLogsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiRequestLogsListResponse`
        """
        model = ApiRequestLogsListResponse()
        if include_optional:
            return ApiRequestLogsListResponse(
                data = [
                    invoicepdfs.models.api_request_log_out.ApiRequestLogOut(
                        id = '', 
                        method = '', 
                        path = '', 
                        query = '', 
                        status_code = 56, 
                        duration_ms = 56, 
                        request_body = '', 
                        response_body = '', 
                        created_at = '', )
                    ]
            )
        else:
            return ApiRequestLogsListResponse(
                data = [
                    invoicepdfs.models.api_request_log_out.ApiRequestLogOut(
                        id = '', 
                        method = '', 
                        path = '', 
                        query = '', 
                        status_code = 56, 
                        duration_ms = 56, 
                        request_body = '', 
                        response_body = '', 
                        created_at = '', )
                    ],
        )
        """

    def testApiRequestLogsListResponse(self):
        """Test ApiRequestLogsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
