# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.deliveries_list_response import DeliveriesListResponse

class TestDeliveriesListResponse(unittest.TestCase):
    """DeliveriesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveriesListResponse:
        """Test DeliveriesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveriesListResponse`
        """
        model = DeliveriesListResponse()
        if include_optional:
            return DeliveriesListResponse(
                data = [
                    invoicepdfs.models.delivery_out.DeliveryOut(
                        id = '', 
                        invoice_id = '', 
                        to = [
                            ''
                            ], 
                        cc = [
                            ''
                            ], 
                        bcc = [
                            ''
                            ], 
                        subject = '', 
                        message = '', 
                        attach_pdf = True, 
                        status = 'queued', 
                        created_at = '', 
                        sent_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return DeliveriesListResponse(
                data = [
                    invoicepdfs.models.delivery_out.DeliveryOut(
                        id = '', 
                        invoice_id = '', 
                        to = [
                            ''
                            ], 
                        cc = [
                            ''
                            ], 
                        bcc = [
                            ''
                            ], 
                        subject = '', 
                        message = '', 
                        attach_pdf = True, 
                        status = 'queued', 
                        created_at = '', 
                        sent_at = '', )
                    ],
        )
        """

    def testDeliveriesListResponse(self):
        """Test DeliveriesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
