# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.batches_list_response import BatchesListResponse

class TestBatchesListResponse(unittest.TestCase):
    """BatchesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchesListResponse:
        """Test BatchesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchesListResponse`
        """
        model = BatchesListResponse()
        if include_optional:
            return BatchesListResponse(
                data = [
                    invoicepdfs.models.batch_out.BatchOut(
                        id = '', 
                        status = 'queued', 
                        operation = '', 
                        template_id = '', 
                        total_items = 56, 
                        completed_items = 56, 
                        failed_items = 56, 
                        created_at = '', 
                        updated_at = '', 
                        completed_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return BatchesListResponse(
                data = [
                    invoicepdfs.models.batch_out.BatchOut(
                        id = '', 
                        status = 'queued', 
                        operation = '', 
                        template_id = '', 
                        total_items = 56, 
                        completed_items = 56, 
                        failed_items = 56, 
                        created_at = '', 
                        updated_at = '', 
                        completed_at = '', )
                    ],
        )
        """

    def testBatchesListResponse(self):
        """Test BatchesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
