# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.invoice_preview_request import InvoicePreviewRequest

class TestInvoicePreviewRequest(unittest.TestCase):
    """InvoicePreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoicePreviewRequest:
        """Test InvoicePreviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoicePreviewRequest`
        """
        model = InvoicePreviewRequest()
        if include_optional:
            return InvoicePreviewRequest(
                invoice_number = 'INV-2026-001',
                document_type = 'invoice',
                issue_date = 'Mon Jul 20 00:00:00 UTC 2026',
                due_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                currency = 'USD',
                locale = '',
                business_profile_id = 'bp_01ABC',
                customer_id = 'cus_01XYZ',
                ship_to = invoicepdfs.models.postal_address.PostalAddress(
                    line1 = '1 Main St', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    postal_code = '', 
                    country = '', ),
                line_items = [
                    invoicepdfs.models.invoice_line_item_input.InvoiceLineItemInput(
                        name = 'Web Development', 
                        description = '', 
                        quantity = '2', 
                        unit_price = '150.00', 
                        unit = '', 
                        sku = '', 
                        discount = invoicepdfs.models.invoice_discount_input.InvoiceDiscountInput(
                            type = 'percentage', 
                            value = '10', 
                            reason = '', ), 
                        taxes = [
                            invoicepdfs.models.invoice_line_item_tax_input.InvoiceLineItemTaxInput(
                                tax_rate_id = '', 
                                name = '', 
                                rate = '', 
                                inclusive = True, )
                            ], )
                    ],
                discounts = [
                    invoicepdfs.models.invoice_discount_input.InvoiceDiscountInput(
                        type = 'percentage', 
                        value = '10', 
                        reason = '', )
                    ],
                shipping = invoicepdfs.models.invoice_shipping_input.InvoiceShippingInput(
                    description = 'Shipping', 
                    amount = '9.99', ),
                notes = [
                    invoicepdfs.models.invoice_note_input.InvoiceNoteInput(
                        type = 'note', 
                        content = 'Thank you for your business!', )
                    ],
                terms = [
                    invoicepdfs.models.invoice_term_input.InvoiceTermInput(
                        type = 'term', 
                        content = 'Net 30 — payment due within 30 days of invoice date.', )
                    ],
                custom_fields = [
                    invoicepdfs.models.invoice_custom_field_input.InvoiceCustomFieldInput(
                        label = 'PO Number', 
                        value = 'PO-2026-001', )
                    ],
                payment = invoicepdfs.models.invoice_payment_input.InvoicePaymentInput(
                    bank_account = invoicepdfs.models.invoice_bank_account_input.InvoiceBankAccountInput(
                        bank_name = '', 
                        account_name = '', 
                        account_number = '', 
                        routing_number = '', 
                        swift = '', 
                        iban = '', ), 
                    payment_url = '', 
                    accepted_methods = ["bank_transfer","credit_card"], 
                    instructions = '', ),
                branding = invoicepdfs.models.invoice_branding_input.InvoiceBrandingInput(
                    logo_file_id = '', 
                    primary_color = '#111827', 
                    accent_color = '#111827', 
                    font_family = '', 
                    footer_text = 'Generated by InvoicePDFs', ),
                template_id = 'tpl_modern',
                page_size = 'LETTER'
            )
        else:
            return InvoicePreviewRequest(
                invoice_number = 'INV-2026-001',
                issue_date = 'Mon Jul 20 00:00:00 UTC 2026',
                currency = 'USD',
                business_profile_id = 'bp_01ABC',
                customer_id = 'cus_01XYZ',
                line_items = [
                    invoicepdfs.models.invoice_line_item_input.InvoiceLineItemInput(
                        name = 'Web Development', 
                        description = '', 
                        quantity = '2', 
                        unit_price = '150.00', 
                        unit = '', 
                        sku = '', 
                        discount = invoicepdfs.models.invoice_discount_input.InvoiceDiscountInput(
                            type = 'percentage', 
                            value = '10', 
                            reason = '', ), 
                        taxes = [
                            invoicepdfs.models.invoice_line_item_tax_input.InvoiceLineItemTaxInput(
                                tax_rate_id = '', 
                                name = '', 
                                rate = '', 
                                inclusive = True, )
                            ], )
                    ],
        )
        """

    def testInvoicePreviewRequest(self):
        """Test InvoicePreviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
