# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.branding_response import BrandingResponse

class TestBrandingResponse(unittest.TestCase):
    """BrandingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandingResponse:
        """Test BrandingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandingResponse`
        """
        model = BrandingResponse()
        if include_optional:
            return BrandingResponse(
                data = invoicepdfs.models.branding_out.BrandingOut(
                    logo_file_id = '', 
                    primary_color = '', 
                    accent_color = '', 
                    font_family = '', 
                    footer_text = '', 
                    hide_invoicepdfs_branding = True, 
                    created_at = '', 
                    updated_at = '', )
            )
        else:
            return BrandingResponse(
                data = invoicepdfs.models.branding_out.BrandingOut(
                    logo_file_id = '', 
                    primary_color = '', 
                    accent_color = '', 
                    font_family = '', 
                    footer_text = '', 
                    hide_invoicepdfs_branding = True, 
                    created_at = '', 
                    updated_at = '', ),
        )
        """

    def testBrandingResponse(self):
        """Test BrandingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
