# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.document_calculate_response import DocumentCalculateResponse

class TestDocumentCalculateResponse(unittest.TestCase):
    """DocumentCalculateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentCalculateResponse:
        """Test DocumentCalculateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentCalculateResponse`
        """
        model = DocumentCalculateResponse()
        if include_optional:
            return DocumentCalculateResponse(
                data = {
                    'key' : invoicepdfs.models.calculation_breakdown.CalculationBreakdown(
                        subtotal = invoicepdfs.models.money.Money(
                            amount = '', 
                            currency = '', ), 
                        discount_total = invoicepdfs.models.money.Money(
                            amount = '', 
                            currency = '', ), 
                        tax_total = , 
                        shipping_total = , 
                        total = , )
                    }
            )
        else:
            return DocumentCalculateResponse(
                data = {
                    'key' : invoicepdfs.models.calculation_breakdown.CalculationBreakdown(
                        subtotal = invoicepdfs.models.money.Money(
                            amount = '', 
                            currency = '', ), 
                        discount_total = invoicepdfs.models.money.Money(
                            amount = '', 
                            currency = '', ), 
                        tax_total = , 
                        shipping_total = , 
                        total = , )
                    },
        )
        """

    def testDocumentCalculateResponse(self):
        """Test DocumentCalculateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
