# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.invoice_line_item_input import InvoiceLineItemInput

class TestInvoiceLineItemInput(unittest.TestCase):
    """InvoiceLineItemInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceLineItemInput:
        """Test InvoiceLineItemInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceLineItemInput`
        """
        model = InvoiceLineItemInput()
        if include_optional:
            return InvoiceLineItemInput(
                name = 'Web Development',
                description = '',
                quantity = '2',
                unit_price = '150.00',
                unit = '',
                sku = '',
                discount = invoicepdfs.models.invoice_discount_input.InvoiceDiscountInput(
                    type = 'percentage', 
                    value = '10', 
                    reason = '', ),
                taxes = [
                    invoicepdfs.models.invoice_line_item_tax_input.InvoiceLineItemTaxInput(
                        tax_rate_id = '', 
                        name = '', 
                        rate = '', 
                        inclusive = True, )
                    ]
            )
        else:
            return InvoiceLineItemInput(
                name = 'Web Development',
                quantity = '2',
                unit_price = '150.00',
        )
        """

    def testInvoiceLineItemInput(self):
        """Test InvoiceLineItemInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
