# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.webhook_deliveries_list_response import WebhookDeliveriesListResponse

class TestWebhookDeliveriesListResponse(unittest.TestCase):
    """WebhookDeliveriesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveriesListResponse:
        """Test WebhookDeliveriesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveriesListResponse`
        """
        model = WebhookDeliveriesListResponse()
        if include_optional:
            return WebhookDeliveriesListResponse(
                data = [
                    invoicepdfs.models.webhook_delivery_out.WebhookDeliveryOut(
                        id = '', 
                        endpoint_id = '', 
                        event_id = '', 
                        event_type = '', 
                        status = 'pending', 
                        http_status = 56, 
                        attempts = 56, 
                        error_message = '', 
                        created_at = '', 
                        delivered_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return WebhookDeliveriesListResponse(
                data = [
                    invoicepdfs.models.webhook_delivery_out.WebhookDeliveryOut(
                        id = '', 
                        endpoint_id = '', 
                        event_id = '', 
                        event_type = '', 
                        status = 'pending', 
                        http_status = 56, 
                        attempts = 56, 
                        error_message = '', 
                        created_at = '', 
                        delivered_at = '', )
                    ],
        )
        """

    def testWebhookDeliveriesListResponse(self):
        """Test WebhookDeliveriesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
