# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.billing_checkout_response import BillingCheckoutResponse

class TestBillingCheckoutResponse(unittest.TestCase):
    """BillingCheckoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingCheckoutResponse:
        """Test BillingCheckoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingCheckoutResponse`
        """
        model = BillingCheckoutResponse()
        if include_optional:
            return BillingCheckoutResponse(
                data = invoicepdfs.models.billing_checkout_data.BillingCheckoutData(
                    session_id = '', 
                    url = '', )
            )
        else:
            return BillingCheckoutResponse(
                data = invoicepdfs.models.billing_checkout_data.BillingCheckoutData(
                    session_id = '', 
                    url = '', ),
        )
        """

    def testBillingCheckoutResponse(self):
        """Test BillingCheckoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
