# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.custom_templates_list_response import CustomTemplatesListResponse

class TestCustomTemplatesListResponse(unittest.TestCase):
    """CustomTemplatesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomTemplatesListResponse:
        """Test CustomTemplatesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomTemplatesListResponse`
        """
        model = CustomTemplatesListResponse()
        if include_optional:
            return CustomTemplatesListResponse(
                data = [
                    invoicepdfs.models.custom_template_out.CustomTemplateOut(
                        id = '', 
                        name = '', 
                        description = '', 
                        base_template_id = '', 
                        config = { }, 
                        status = '', 
                        is_default = True, 
                        created_at = '', 
                        updated_at = '', 
                        published_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return CustomTemplatesListResponse(
                data = [
                    invoicepdfs.models.custom_template_out.CustomTemplateOut(
                        id = '', 
                        name = '', 
                        description = '', 
                        base_template_id = '', 
                        config = { }, 
                        status = '', 
                        is_default = True, 
                        created_at = '', 
                        updated_at = '', 
                        published_at = '', )
                    ],
        )
        """

    def testCustomTemplatesListResponse(self):
        """Test CustomTemplatesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
