# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file_api_v1_files_file_id_delete(self) -> None:
        """Test case for delete_file_api_v1_files_file_id_delete

        Delete File
        """
        pass

    def test_get_file_api_v1_files_file_id_get(self) -> None:
        """Test case for get_file_api_v1_files_file_id_get

        Get File
        """
        pass

    def test_upload_file_api_v1_files_post(self) -> None:
        """Test case for upload_file_api_v1_files_post

        Upload File
        """
        pass


if __name__ == '__main__':
    unittest.main()
