# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.customer_patch import CustomerPatch

class TestCustomerPatch(unittest.TestCase):
    """CustomerPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerPatch:
        """Test CustomerPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerPatch`
        """
        model = CustomerPatch()
        if include_optional:
            return CustomerPatch(
                name = '',
                email = '',
                phone = '',
                tax_id = '',
                billing_address = invoicepdfs.models.postal_address.PostalAddress(
                    line1 = '1 Main St', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    postal_code = '', 
                    country = '', ),
                shipping_address = invoicepdfs.models.postal_address.PostalAddress(
                    line1 = '1 Main St', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    postal_code = '', 
                    country = '', ),
                metadata = { }
            )
        else:
            return CustomerPatch(
        )
        """

    def testCustomerPatch(self):
        """Test CustomerPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
