# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.batch_create_request import BatchCreateRequest

class TestBatchCreateRequest(unittest.TestCase):
    """BatchCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchCreateRequest:
        """Test BatchCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchCreateRequest`
        """
        model = BatchCreateRequest()
        if include_optional:
            return BatchCreateRequest(
                operation = 'render',
                items = [
                    invoicepdfs.models.batch_item_input.BatchItemInput(
                        external_id = '', 
                        document_type = 'invoice', 
                        data = { }, )
                    ],
                template_id = 'tpl_modern',
                output = invoicepdfs.models.batch_output_options.BatchOutputOptions(
                    format = 'pdf', 
                    combine = True, 
                    archive_format = 'zip', )
            )
        else:
            return BatchCreateRequest(
                items = [
                    invoicepdfs.models.batch_item_input.BatchItemInput(
                        external_id = '', 
                        document_type = 'invoice', 
                        data = { }, )
                    ],
        )
        """

    def testBatchCreateRequest(self):
        """Test BatchCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
