# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.auth_refresh_data import AuthRefreshData

class TestAuthRefreshData(unittest.TestCase):
    """AuthRefreshData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthRefreshData:
        """Test AuthRefreshData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthRefreshData`
        """
        model = AuthRefreshData()
        if include_optional:
            return AuthRefreshData(
                id_token = '',
                refresh_token = '',
                expires_in = 56
            )
        else:
            return AuthRefreshData(
                id_token = '',
                refresh_token = '',
                expires_in = 56,
        )
        """

    def testAuthRefreshData(self):
        """Test AuthRefreshData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
