# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.document_attachments_api import DocumentAttachmentsApi


class TestDocumentAttachmentsApi(unittest.TestCase):
    """DocumentAttachmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentAttachmentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_document_attachment(self) -> None:
        """Test case for create_document_attachment

        Create Document Attachment
        """
        pass

    def test_delete_document_attachment(self) -> None:
        """Test case for delete_document_attachment

        Delete Document Attachment
        """
        pass

    def test_list_document_attachments(self) -> None:
        """Test case for list_document_attachments

        List Document Attachments
        """
        pass


if __name__ == '__main__':
    unittest.main()
