# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.billing_plan import BillingPlan

class TestBillingPlan(unittest.TestCase):
    """BillingPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingPlan:
        """Test BillingPlan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingPlan`
        """
        model = BillingPlan()
        if include_optional:
            return BillingPlan(
                id = '',
                name = '',
                price_id = '',
                monthly_render_quota = 56
            )
        else:
            return BillingPlan(
                id = '',
                name = '',
                price_id = '',
                monthly_render_quota = 56,
        )
        """

    def testBillingPlan(self):
        """Test BillingPlan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
