# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.tax_rate_out import TaxRateOut

class TestTaxRateOut(unittest.TestCase):
    """TaxRateOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxRateOut:
        """Test TaxRateOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxRateOut`
        """
        model = TaxRateOut()
        if include_optional:
            return TaxRateOut(
                id = '',
                name = '',
                rate = '',
                inclusive = True,
                jurisdiction = '',
                is_active = True,
                created_at = '',
                updated_at = ''
            )
        else:
            return TaxRateOut(
                id = '',
                name = '',
                rate = '',
                inclusive = True,
                is_active = True,
                created_at = '',
                updated_at = '',
        )
        """

    def testTaxRateOut(self):
        """Test TaxRateOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
