# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.auth_refresh_request import AuthRefreshRequest

class TestAuthRefreshRequest(unittest.TestCase):
    """AuthRefreshRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthRefreshRequest:
        """Test AuthRefreshRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthRefreshRequest`
        """
        model = AuthRefreshRequest()
        if include_optional:
            return AuthRefreshRequest(
                refresh_token = ''
            )
        else:
            return AuthRefreshRequest(
                refresh_token = '',
        )
        """

    def testAuthRefreshRequest(self):
        """Test AuthRefreshRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
