# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.usage_limits_data import UsageLimitsData

class TestUsageLimitsData(unittest.TestCase):
    """UsageLimitsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageLimitsData:
        """Test UsageLimitsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageLimitsData`
        """
        model = UsageLimitsData()
        if include_optional:
            return UsageLimitsData(
                renders = invoicepdfs.models.usage_render_limits.UsageRenderLimits(
                    used = 56, 
                    limit = 56, 
                    remaining = 56, ),
                rate_limit = invoicepdfs.models.usage_rate_limit.UsageRateLimit(
                    requests_per_second = 56, )
            )
        else:
            return UsageLimitsData(
                renders = invoicepdfs.models.usage_render_limits.UsageRenderLimits(
                    used = 56, 
                    limit = 56, 
                    remaining = 56, ),
                rate_limit = invoicepdfs.models.usage_rate_limit.UsageRateLimit(
                    requests_per_second = 56, ),
        )
        """

    def testUsageLimitsData(self):
        """Test UsageLimitsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
