# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.credit_notes_list_response import CreditNotesListResponse

class TestCreditNotesListResponse(unittest.TestCase):
    """CreditNotesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditNotesListResponse:
        """Test CreditNotesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditNotesListResponse`
        """
        model = CreditNotesListResponse()
        if include_optional:
            return CreditNotesListResponse(
                data = [
                    invoicepdfs.models.credit_note_out.CreditNoteOut(
                        id = '', 
                        invoice_id = '', 
                        credit_note_number = '', 
                        status = 'draft', 
                        reason = '', 
                        currency = '', 
                        totals = invoicepdfs.models.invoice_totals_out.InvoiceTotalsOut(
                            subtotal = invoicepdfs.models.money_out.MoneyOut(
                                amount = '', 
                                currency = '', ), 
                            discount_total = invoicepdfs.models.money_out.MoneyOut(
                                amount = '', 
                                currency = '', ), 
                            tax_total = , 
                            shipping_total = , 
                            total = , ), 
                        issue_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        created_at = '', 
                        updated_at = '', 
                        finalized_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return CreditNotesListResponse(
                data = [
                    invoicepdfs.models.credit_note_out.CreditNoteOut(
                        id = '', 
                        invoice_id = '', 
                        credit_note_number = '', 
                        status = 'draft', 
                        reason = '', 
                        currency = '', 
                        totals = invoicepdfs.models.invoice_totals_out.InvoiceTotalsOut(
                            subtotal = invoicepdfs.models.money_out.MoneyOut(
                                amount = '', 
                                currency = '', ), 
                            discount_total = invoicepdfs.models.money_out.MoneyOut(
                                amount = '', 
                                currency = '', ), 
                            tax_total = , 
                            shipping_total = , 
                            total = , ), 
                        issue_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        created_at = '', 
                        updated_at = '', 
                        finalized_at = '', )
                    ],
        )
        """

    def testCreditNotesListResponse(self):
        """Test CreditNotesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
