# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.auth_me_account import AuthMeAccount

class TestAuthMeAccount(unittest.TestCase):
    """AuthMeAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthMeAccount:
        """Test AuthMeAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthMeAccount`
        """
        model = AuthMeAccount()
        if include_optional:
            return AuthMeAccount(
                id = '',
                name = '',
                plan_id = '',
                plan_name = ''
            )
        else:
            return AuthMeAccount(
                id = '',
                name = '',
                plan_id = '',
                plan_name = '',
        )
        """

    def testAuthMeAccount(self):
        """Test AuthMeAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
