# coding: utf-8

"""
    InvoicePDFs

    InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.api.branding_profiles_api import BrandingProfilesApi


class TestBrandingProfilesApi(unittest.TestCase):
    """BrandingProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandingProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_branding_profile(self) -> None:
        """Test case for create_branding_profile

        Create Branding Profile
        """
        pass

    def test_delete_branding_logo(self) -> None:
        """Test case for delete_branding_logo

        Delete Branding Logo
        """
        pass

    def test_delete_branding_profile(self) -> None:
        """Test case for delete_branding_profile

        Delete Branding Profile
        """
        pass

    def test_get_branding_profile(self) -> None:
        """Test case for get_branding_profile

        Get Branding Profile
        """
        pass

    def test_list_branding_profiles(self) -> None:
        """Test case for list_branding_profiles

        List Branding Profiles
        """
        pass

    def test_set_default_branding_profile(self) -> None:
        """Test case for set_default_branding_profile

        Set Default Branding Profile
        """
        pass

    def test_update_branding_profile(self) -> None:
        """Test case for update_branding_profile

        Update Branding Profile
        """
        pass

    def test_upload_branding_logo(self) -> None:
        """Test case for upload_branding_logo

        Upload Branding Logo
        """
        pass


if __name__ == '__main__':
    unittest.main()
