# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.payments_list_response import PaymentsListResponse

class TestPaymentsListResponse(unittest.TestCase):
    """PaymentsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentsListResponse:
        """Test PaymentsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentsListResponse`
        """
        model = PaymentsListResponse()
        if include_optional:
            return PaymentsListResponse(
                data = [
                    invoicepdfs.models.payment_out.PaymentOut(
                        id = '', 
                        invoice_id = '', 
                        amount = invoicepdfs.models.money_out.MoneyOut(
                            amount = '', 
                            currency = '', ), 
                        paid_at = '', 
                        method = '', 
                        reference = '', 
                        notes = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
                pagination = invoicepdfs.models.cursor_pagination.CursorPagination(
                    has_more = True, 
                    next_cursor = '', )
            )
        else:
            return PaymentsListResponse(
                data = [
                    invoicepdfs.models.payment_out.PaymentOut(
                        id = '', 
                        invoice_id = '', 
                        amount = invoicepdfs.models.money_out.MoneyOut(
                            amount = '', 
                            currency = '', ), 
                        paid_at = '', 
                        method = '', 
                        reference = '', 
                        notes = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testPaymentsListResponse(self):
        """Test PaymentsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
