# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.document_custom_field_input import DocumentCustomFieldInput

class TestDocumentCustomFieldInput(unittest.TestCase):
    """DocumentCustomFieldInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentCustomFieldInput:
        """Test DocumentCustomFieldInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentCustomFieldInput`
        """
        model = DocumentCustomFieldInput()
        if include_optional:
            return DocumentCustomFieldInput(
                label = 'PO Number',
                value = 'PO-2026-001'
            )
        else:
            return DocumentCustomFieldInput(
                label = 'PO Number',
                value = 'PO-2026-001',
        )
        """

    def testDocumentCustomFieldInput(self):
        """Test DocumentCustomFieldInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
