# coding: utf-8

"""
    InvoicePDFs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from invoicepdfs.models.credit_note_create_request import CreditNoteCreateRequest

class TestCreditNoteCreateRequest(unittest.TestCase):
    """CreditNoteCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditNoteCreateRequest:
        """Test CreditNoteCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditNoteCreateRequest`
        """
        model = CreditNoteCreateRequest()
        if include_optional:
            return CreditNoteCreateRequest(
                invoice_id = 'inv_01ABC',
                credit_note_number = 'CN-2026-001',
                issue_date = 'Mon Jul 20 00:00:00 UTC 2026',
                reason = '',
                line_items = [
                    invoicepdfs.models.credit_note_line_item_input.CreditNoteLineItemInput(
                        name = 'Web Development', 
                        description = '', 
                        quantity = '1', 
                        unit_price = '150.00', 
                        taxes = [
                            invoicepdfs.models.invoice_line_item_tax_input.InvoiceLineItemTaxInput(
                                tax_rate_id = '', 
                                name = '', 
                                rate = '', 
                                inclusive = True, )
                            ], )
                    ]
            )
        else:
            return CreditNoteCreateRequest(
                invoice_id = 'inv_01ABC',
                credit_note_number = 'CN-2026-001',
                issue_date = 'Mon Jul 20 00:00:00 UTC 2026',
                line_items = [
                    invoicepdfs.models.credit_note_line_item_input.CreditNoteLineItemInput(
                        name = 'Web Development', 
                        description = '', 
                        quantity = '1', 
                        unit_price = '150.00', 
                        taxes = [
                            invoicepdfs.models.invoice_line_item_tax_input.InvoiceLineItemTaxInput(
                                tax_rate_id = '', 
                                name = '', 
                                rate = '', 
                                inclusive = True, )
                            ], )
                    ],
        )
        """

    def testCreditNoteCreateRequest(self):
        """Test CreditNoteCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
